### ISSUE TITLE
redis server freezes

### ISSUE THREAD

**Issue by marvin-kolja** [Mavial/theglobe_scraper#27]
the implentation of the redis server doesn't allow scrapy to be interrupted by keyboard. There has to be a _close_connection_ function inside the code when scrapy closes the spider to have a clean closing of the connection.

**Comment by marvin-kolja** [comment]
> 
> 
> the implentation of the redis server doesn't allow scrapy to be interrupted by keyboard. There has to be a _close_connection_ function inside the code when scrapy closes the spider to have a clean closing of the connection.

This issue can have it's server-wise too. @leonrudowicz Maybe you can post the error that gets thrown.

**Comment by Mavial** [comment]
fixed by hosting it outside a docker container
